const DOM={timelineStatus:document.getElementById('timeline-status'),commitList:document.getElementById('commit-list'),lastUpdated:document.getElementById('page-last-updated')};
const MEDIA={YOUTUBE:{pattern:/(?:v=|youtu\.be\/)([\w-]+)/,embed:id=>`<div class="media-container"><iframe width="100%" height="200" src="https://www.youtube.com/embed/${id}" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>`},SOUNDCLOUD:{pattern:/https:\/\/soundcloud\.com\/[a-zA-Z0-9-_]+\/[a-zA-Z0-9-_]+/,embed:url=>`<div class="media-container"><iframe width="100%" height="200" scrolling="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=${encodeURIComponent(url)}&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe></div>`},IMAGE:{pattern:/\bhttps?:\/\/\S+\.(?:jpg|jpeg|png|gif)\b/,embed:url=>`<div class="media-container"><img src="${url}" alt="Timeline Media" class="timeline-image"></div>`}};
const formatDate=d=>new Date(d).toLocaleString();
const parseDate=s=>new Date(s);
const stripUrls=t=>t.replace(/https?:\/\/[^\s]+/g,'');
async function displayTimelineEntry(){try{if(!DOM.timelineStatus)throw new Error('Timeline status element not found');const r=await fetch('timeline.json');const t=await r.json();const e=t.sort((a,b)=>parseDate(b.time)-parseDate(a.time))[0];const m=mediaFromText(e.text);const c=stripUrls(e.text);const d=formatDate(e.time);DOM.timelineStatus.innerHTML=`<span>${d}</span><div>${c}</div>${m}`;}catch(err){console.error('Error in timeline display:',err);}}
function mediaFromText(txt){for(const type of Object.values(MEDIA)){const match=txt.match(type.pattern);if(match)return type.embed(match[1]||match[0]);}return'';}
async function displayRecentCommits(){try{const r=await fetch('commits.json');const c=await r.json();const list=c.sort((a,b)=>parseDate(b.date)-parseDate(a.date)).slice(0,5);DOM.commitList.innerHTML=list.map(commit=>`<tr><td>${formatDate(commit.date)}</td><td>${commit.author}</td><td>${commit.message}</td></tr>`).join('');}catch(err){console.error('Error fetching commits:',err);}}
async function displayLastUpdated(){try{const r=await fetch('index.html',{method:'HEAD'});const lastMod=new Date(r.headers.get('last-modified'));DOM.lastUpdated.textContent=formatDate(lastMod);}catch(err){console.error('Error fetching last updated date:',err);}}
document.addEventListener('DOMContentLoaded',()=>{displayTimelineEntry();displayRecentCommits();displayLastUpdated();});