name: Update Commits File

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch recent commits and save to JSON
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               "https://api.github.com/repos/jurietto/jurietto.github.io/commits?per_page=50" \
          | jq '[.[] | select(.commit.author.name == "jurietto") | {
              author: .commit.author.name,
              date: .commit.author.date,
              message: .commit.message
          }]' > commits.json

      - name: Commit and push commits.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jurietto/jurietto.github.io.git
          git add commits.json
          git diff --cached --quiet || git commit -m "Update commit log [bot]"
          git push origin main

