name: Update Commits File

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch recent commits by jurietto and save to JSON
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
               https://api.github.com/repos/jurietto/jurietto.github.io/commits?per_page=100 \
          | jq '[.[] | select(.author.login == "jurietto") | {
              author: .commit.author.name,
              date: .commit.author.date,
              message: .commit.message
          }][0:50]' > commits.json

      - name: Commit and push commits.json
        run: |
          git config user.name "jurietto"
          git config user.email "your-email@example.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jurietto/jurietto.github.io.git
          git fetch origin main
          git rebase origin/main
          git add commits.json
          git diff --cached --quiet || git commit -m "Update commit log"
          git push origin main
