name: Update Commits File

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 👈 REQUIRED to push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch recent commits and save to JSON
  run: |
    curl -s -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/jurietto/jurietto.github.io/commits?per_page=10 \
    | jq '[.[] | select(type == "object" and .commit) | {
        message: .commit.message,
        author: .commit.author.name,
        date: .commit.author.date,
        url: .html_url
    }]' > commits.json


      - name: Commit and push commits.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add commits.json
          git diff --cached --quiet || git commit -m "Update commit log [bot]"
          git push
