name: Update Commits File

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch recent commits and save to JSON
        run: |
          curl -s https://api.github.com/repos/${{ github.repository }}/commits?per_page=10 \
          | jq '[.[] | {message: .commit.message, author: .commit.author.name, date: .commit.author.date, url: .html_url}]' \
          > commits.json

      - name: Commit and push commits.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add commits.json
          git diff --cached --quiet && echo "No changes" || git commit -m "Update commit log [bot]"
          git push
