name: Update Commits JSON

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  schedule:
    - cron: '0 * * * *'  # Run every hour to ensure your commits are always up to date

jobs:
  update_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the commits from this year
      run: |
        # Get all commits from this year (January 1st to today)
        git log --since="Jan 1, $(date +'%Y')" --pretty=format:'{
          "author": "%an",
          "message": "%s",
          "date": "%ad",
          "files_changed": [%(git show --name-only --oneline --pretty=format:"" --no-patch %h | tail -n +2 | jq -R . | jq -s .)%]
        }' --date=iso > commits.json

        # Use jq to ensure proper formatting
        jq -s '.' commits.json > commits.json.pretty && mv commits.json.pretty commits.json
