name: Update Commit Log

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all 2024 commits by jurietto and save to commits.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          PAGE=1
          echo "[]" > commits.json
          while : ; do
            RESPONSE=$(curl -s -H "Authorization: token $GH_PAT" \
              "https://api.github.com/repos/jurietto/jurietto.github.io/commits?author=jurietto&since=2024-01-01T00:00:00Z&until=2024-12-31T23:59:59Z&per_page=100&page=$PAGE")
            
            COUNT=$(echo "$RESPONSE" | jq length)
            if [ "$COUNT" -eq 0 ]; then
              break
            fi

            echo "$RESPONSE" | jq '[.[] | {
              author: .commit.author.name,
              date: .commit.author.date,
              message: .commit.message
            }]' > temp_commits.json

            # Merge into commits.json
            jq -s '.[0] + .[1]' commits.json temp_commits.json > temp_merged.json && mv temp_merged.json commits.json

            PAGE=$((PAGE + 1))
          done

      - name: Commit and push if changed
        run: |
          git config user.name "jurietto"
          git config user.email "jurilikes2eatcurry@gmail.com"
          git add commits.json
          git diff --cached --quiet || git commit -m "Refresh commit log for 2024"
          git push

