name: Update commits.json

on:
  push:
    branches:
      - main

jobs:
  update-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Commit Info and Update JSON
        run: |
          # Fetch commit details
          commits=$(git log --pretty=format:'{"commit": "%H", "author": "%an", "date": "%ad", "message": "%s"}' --date=iso)

          # Format the commits into a JSON array
          commits_json="[$commits]"

          # Write to commits.json
          echo "$commits_json" > commits.json

      - name: Commit and Push Updated commits.json
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'commits.json'
          message: 'Update commits.json with latest commits'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
