name: Update Commit Log

on:
  push:
    branches: [main]

jobs:
  update-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all commits by jurietto
        run: |
          echo "[" > commits.json
          page=1
          first=true
          while :; do
            res=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
              "https://api.github.com/repos/jurietto/jurietto.github.io/commits?per_page=100&page=$page")
            
            count=$(echo "$res" | jq 'length')
            [ "$count" -eq 0 ] && break

            filtered=$(echo "$res" | jq '[.[] | select(.author.login == "jurietto") | {
              author: .commit.author.name,
              date: .commit.author.date,
              message: .commit.message
            }]')

            if [ "$first" = true ]; then
              echo "$filtered" | jq -c '.[]' >> commits.json
              first=false
            else
              echo "," >> commits.json
              echo "$filtered" | jq -c '.[]' >> commits.json
            fi

            page=$((page + 1))
          done
          echo "]" >> commits.json

      - name: Commit and push if changed
        run: |
          git config user.name "jurietto"
          git config user.email "jurilikes2eatcurry@gmail.com"
          git add commits.json
          git diff --cached --quiet || git commit -m "Update commit log"
          git push
