name: Update Commit Log

on:
  push:
    branches: [main]

jobs:
  update-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all commits by jurietto
        run: |
          echo "[" > commits.json
          page=1
          first=true
          while :
          do
            response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
              "https://api.github.com/repos/jurietto/jurietto.github.io/commits?per_page=100&page=$page")

            count=$(echo "$response" | jq length)
            if [ "$count" -eq 0 ]; then
              break
            fi

            echo "$response" | jq -c '.[] | select(.author.login == "jurietto") | {
              author: .commit.author.name,
              date: .commit.author.date,
              message: .commit.message
            }' | while read -r line; do
              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> commits.json
              fi
              echo "$line" >> commits.json
            done
            page=$((page+1))
          done
          echo "]" >> commits.json

      - name: Commit and push if changed
        run: |
          git config user.name "jurietto"
          git config user.email "jurilikes2eatcurry@gmail.com"
          git add commits.json
          git diff --cached --quiet || git commit -m "Update commit log"
          git push
